P3121 Shukurov Shukurullo task-2
thejerome/IFMO_CPP_programming_20180910 pull request #70
Opened 2018-10-13 20:46 UTC by root5427

2018-12-14 19:23 UTC, thejerome commented on src/main/cpp/t10_sort3.cpp
> +    if(a > b) a ^= b ^= a ^= b;
в продакшне за такое бил бы по рукам.
Но здесь приму.

2018-12-14 19:24 UTC, thejerome requested changes
Нельзя abs, swap, etc.

2018-12-14 20:48 UTC, root5427 commented
+ commit с прекращением использования abs, swap, etc.

2018-12-14 20:50 UTC, root5427 commented
\+ commit с прекращением использования abs, swap, etc.

2018-12-14 20:52 UTC, root5427 commented on src/main/cpp/t10_sort3.cpp
> +    if(a > b) a ^= b ^= a ^= b;
Понял) Просто только перехожу со спорта на продакшн

2018-12-19 19:41 UTC, thejerome approved these changes

2022-05-18 14:01 UTC, closed without merging